# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7zPGCsJYenDUi5pfMw4O_lWZyrxpf5X
"""

#pelo longo
#perna curta
#faz auau
porc1 = [0, 1, 0]
porc2 = [0, 1, 1]
porc3 = [1, 1, 0]

cac1 = [0, 1, 1]
cac2 = [1, 0, 1]
cac3 = [1, 1, 1]

data = [porc1,porc2,porc3,cac1,cac2,cac3]
classes = [1,1,1,0,0,0]

from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(data,classes)

pre = model.predict([[1,1,1],[1,1,0],[0,1,1]])

from sklearn.metrics import accuracy_score

print(accuracy_score([0,1,1], pre))

import pandas as pd

data = pd.read_csv('https://gist.githubusercontent.com/guilhermesilveira/2d2efa37d66b6c84a722ea627a897ced/raw/10968b997d885cbded1c92938c7a9912ba41c615/tracking.csv')

x = data[['home', 'how_it_works', 'contact']]
y = data[['bought']]

print(data.shape)
treino_x = x[:75]
treino_y = y[:75]

test_x = x[75:]
test_y = y[75:]

from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(treino_x,treino_y)

from sklearn.metrics import accuracy_score

prev = model.predict(test_x)
print(accuracy_score(test_y, prev))